### PR TITLE
Features: Added the logo for the landing page and a field to insert a token.

### PR DESCRIPTION
**Pull request by mynavu**
## Summary

This PR adds the logo for the landing page and a field to insert a token as mentioned in the "Landing page/Log-in with token" task. Now, only players who entered '000' or '999' into the token field can play the game.

## Checklist
- [x] I have tested this change locally and it works as expected.
- [x] I have made sure that the code follows the formatting and style guidelines of the project.

## Labels
`type: enhancement`, `area: gameplay`

### CODE REVIEW

**Comment by sloukit** [comment]
The code runs on my system. Some feedback:
- I think you can remove the UZH logo completely. We don't need it here.
- A blinking text cursor in the token field might improve the user interface.
- I would either activate the gray "play" button when a valid token is inserted, or add a "insert token and press enter" text.

**Comment by mynavu** [comment]
> The code runs on my system. Some feedback:
> 
> * I think you can remove the UZH logo completely. We don't need it here.
> * A blinking text cursor in the token field might improve the user interface.
> * I would either activate the gray "play" button when a valid token is inserted, or add a "insert token and press enter" text.

I've removed the logo and changed the landing page so that after the user entered the valid token they can press play. I also added the blinking text cursor in the token field.

**Comment by sloukit** [comment]
Looks totally fine to me, I think the wording is good like that.

**Comment by DangerousVanilla** [comment]
Any chance you could also make the numpad enter key work like the standard one? Currently it's inserting a box character instead: 
image

**Comment by mynavu** [comment]
> Any chance you could also make the numpad enter key work like the standard one? Currently it's inserting a box character instead: image

It doesn't look like a box on my screen but theres another way to make the blinking text cursor using the pygame GUI module. I tried to use the module but too many bugs came up. You're welcome to try and fix it that way. Heres what it looks like on my screen: 
Screenshot 2024-09-28 at 11 37 49 AM

**Comment by sloukit** [comment]
> > Any chance you could also make the numpad enter key work like the standard one? Currently it's inserting a box character instead: image
> 
> It doesn't look like a box on my screen but theres another way to make the blinking text cursor using the pygame GUI module. I tried to use the module but too many bugs came up. You're welcome to try and fix it that way. Heres what it looks like on my screen: Screenshot 2024-09-28 at 11 37 49 AM

It looks like this on my system too.

**Comment by DangerousVanilla** [comment]
My apologies if that wasn't clear - there is no issue with the blinking cursor, however, when you press the enter key on the numpad it creates that box character, as opposed to using the enter key just above the right shift key acting correctly and submitting the token. Here's a quick visual redo that also shows the blinking cursor:

numpad_enter_key_behavior

The keypad enter key can be checked using 'pygame.K_KP_ENTER' so you could just update line 150 of src/gui/menu/general_menu.py to check both and be good to go:
image

**Comment by mynavu** [comment]
> My apologies if that wasn't clear - there is no issue with the blinking cursor, however, when you press the enter key on the numpad it creates that box character, as opposed to using the enter key just above the right shift key acting correctly and submitting the token. Here's a quick visual redo that also shows the blinking cursor:
> 
> numpad_enter_key_behavior
> 
> The keypad enter key can be checked using 'pygame.K_KP_ENTER' so you could just update line 150 of src/gui/menu/general_menu.py to check both and be good to go: image

Thanks for the clarification + feedback. I've just applied that code.

**Review by sloukit — APPROVED** [review]
Looks good. Thanks for the code line, @DangerousVanilla.

@mynavu there seems to be a bug with the style lint test, can you check it please?

**Comment by mynavu** [comment]
> Looks good. Thanks for the code line, @DangerousVanilla.
> 
> @mynavu there seems to be a bug with the style lint test, can you check it please?

Yes, it seems I forgot to run ruff format --fix. I believe I've fixed the issue.

**Comment by sloukit** [comment]
Great, thank you

**Pull request merged**
