### PR TITLE
implementation of readable signposts using DialogManager #144

### PR DESCRIPTION
**Pull request by HubertReX**
## Summary

This PR implements the "[Insert signposts on the maps](https://github.com/users/sloukit/projects/1/views/1?pane=issue&itemId=81013884)" task and relates to #144.

- On the `Farm_new` map, above signs, there are new rect objects on the `Interactions` layer named `sign` with custom property `label`
- This label is used as a key mapped to the character name to trigger `DialogManager` - a bit hacky, but actually looks clean
- the `Sprite` class has been extended to store **custom properties** read from `TiledMap`

## Media

Signpost_text

## Checklist

- [* ] I have tested this change locally and it works as expected.
- [*] I have made sure that the code follows the formatting and style guidelines of the project.

## Labels
`type: feature`, `game-signpost`

### CODE REVIEW

**Comment by HubertReX** [comment]
the read signpost screen (Dialog) is triggered using `Interact` action (`space`)

**Review by sloukit — COMMENTED** [review]
Could you also insert the respective graphics from [here](https://github.com/sloukit/asset-packs/tree/main/Sign%20Emoji)?

**Comment by HubertReX** [comment]
New signpost graphics adde

**Review by sloukit — APPROVED** [review]

**Comment by sloukit** [comment]
Thank you, this looks good! 

- There are many random signs on the minigame map, is this intended? I think we should remove them

**Comment by HubertReX** [comment]
> Thank you, this looks good!
> 
> * There are many random signs on the minigame map, is this intended? I think we should remove them

@sloukit which ones do consider random? Please let me know which exactly we should remove,
I've added a few just by the map borders since they seemed to fit naturally with the new emojis.
There were also some signs on the Town map, but on the wrong layer in Tiled, so they didn't show in the actual game (e.g. Merchant). Should I remove those as well?

**Pull request merged**
