### PR TITLE
Ajusting collisions

### PR DESCRIPTION
**Pull request by raphael-pietrzak**
•	Improved the player animation system.
	•	Enhanced the hitbox functionality for better collision detection. (picture 2)
	•	Main layer based on bottom hitbox
	•	Created a test function to draw rectangles and hitboxes when the [T] key is pressed. (picture 1)
	•	draw apples with the tree, utilizing the sprite.draw(offset) method.
	•	Added a feature to display a preview of farmable tiles. (picture 3)
	•	Now the tile hoed is the tile where the player is : more intuitive
	•	Fixed an issue where the tile preview would only be drawn if the tile is not hoed.
	
Screenshot 2024-07-09 at 01 39 24 Screenshot 2024-07-09 at 06 13 15 Screenshot 2024-07-09 at 19 05 08

Solving #35 Issue

### CODE REVIEW

**Comment by raphael-pietrzak** [comment]
sure i add it on settings menu keybinds so it can be changed by anyone, i will change the default key anyway

**Review by fortwoone — CHANGES_REQUESTED** [review]
In addition to the changes Manunz15 has requested, the code structure has changed dramatically. You should probably rebase your work on the main branch as well, so that the merge conflicts get resolved

**Comment by raphael-pietrzak** [comment]
> In addition to the changes Manunz15 has requested, the code structure has changed dramatically. You should probably rebase your work on the main branch as well, so that the merge conflicts get resolved

sure but i need #54 PR to be merged to rebase this PR because this PR is linked

**Comment by fortwoone** [comment]
Would you mind explaining how they are linked?

**Comment by fortwoone** [comment]
> > In addition to the changes Manunz15 has requested, the code structure has changed dramatically. You should probably rebase your work on the main branch as well, so that the merge conflicts get resolved
> 
> sure but i need #54 PR to be merged to rebase this PR because this PR is linked

After reviewing PR 54, there is no reason for them to be linked. Why would refactoring a completely different part of the game affect collision changes?

**Comment by raphael-pietrzak** [comment]
I think this can be deleted because all these changes are in #70 #72 and #73, i will add the tile preview rect and this is already done but i need #72 hitboxes to be merged to PR (or should i rebase on #72 PR?)

**Pull request closed without merging**
