### PR TITLE
Fast forward option for cutscenes

### PR DESCRIPTION
**Pull request by bucket91**
## Summary

Added feature to skip/fast forward through cut scenes at 5x speed   .

https://github.com/user-attachments/assets/6f89bbd9-7364-4ffc-b367-c3006dcec067

## Labels
`type: ...`, `area: ...`, `game-...`, ...

### CODE REVIEW

**Review by tank-king — CHANGES_REQUESTED** [review]
Very Helpful for skipping the intro cutscene for repeated debugging.

However there are some concerns regarding multiplying dt by 5:
- potential inaccurate collision checking in cutscenes
- skipped or missed animation triggers

Also, class name should be FastForward based on PEP guidelines.

The text surface "R_SHIFT to skip" can be cached in the FastForward class to prevent re-rendering each frame.

I suggest capping dt and processing in chunks, i.e.
instead of game_update(dt * 5)
we can do:
```py
for i in range(5):
   game_update(dt)
```

Some other reviewer please write your feedback on this.

**Comment by bucket91** [comment]
@tank-king check the changes.

**Comment by bucket91** [comment]
Don't review until tomorrow, further changes are required.

**Comment by bucket91** [comment]
Done! Proceed with the review

**Comment by tank-king** [comment]
This looks pretty good.
However, there seems to be an issue. I expected base game to run at 120 FPS approx, but it runs at 55-60 FPS on my machine. Unfortunately, because of this, when you add multiple updates with dt, it slows down the FPS to 20, making the cutscene look choppy.
Taking this into consideration, I would request you to revert to the old method of update(dt * 5). However, that means everything else in the game must scale accordingly without skipping logic, but as for the context of this PR, this should suffice.

Also please change the name of the class to `FastForward` based on PEP Guidelines for class names.

**Comment by bucket91** [comment]
@tank-king check now.

**Review by tank-king — APPROVED** [review]
This looks great! Thanks for your hard work. 
I’m approving it now, but we might need to make minor changes in the future to ensure that the resource path is used instead of the raw path. This will help maintain cross-platform compatibility when running from any OS, whether it’s a web environment or a PyInstaller bundle.

**Review by DangerousVanilla — COMMENTED** [review]
@tank-king, just reviewing at your request here post merge. Seems like the feature got implemented well. 
The only thing I noticed that isn't really issues, just an observation:
- The on screen help text for fast-forwarding says 'R_Shift to skip" but you're not _technically_ skipping the animation.

I like the feature and am really glad to have it, especially for testing!

**Comment by tank-king** [comment]
Yes I saw that issue too. I have kept it on low priority for now so that the merge can be done quickly, but we need to sort that out. I will probably make a new PR or suggest @bucket91 to make the necessary adjustments later.

**Comment by bucket91** [comment]
Done with PR#204. But "Give the player a Hat also counts as a cutscene. So the fast forward option in that situation seems weird. what to do about that?

**Comment by sloukit** [comment]
@bucket91 totally agree, we should remove the option to fast forward in the cutscenes where members receive items. Can you do this?

**Pull request merged**
