### PR TITLE
added round end screen

### PR DESCRIPTION
**Pull request by ylhs-262912**
Please go the the `Preview` tab and select the appropriate sub-template:

* [Features/Enhancements/Fixes](?expand=1&template=code_pr_template.md) 
added round end screen with a timer between rounds of 15 mins

### CODE REVIEW

**Review by sloukit — CHANGES_REQUESTED** [review]
Code looks good to me. Requested changes:
- Add a keybind to immediately go to the end of a round (will be useful for testing)

**Review by DangerousVanilla — CHANGES_REQUESTED** [review]
Most of this looks good but the statistics on the round end screen appear to be displaying the starting inventory values, not 'how many plants and fruit have been planted/harvested' as listed in the feature requirement.

Before approval, please address the items below:
- Fix which items are displayed in the statistics (will require keeping track of which things are planted and harvested, preferrably independantly).
- Ensure proper end-user friendly names are being displayed in statistics (i.e. 'Corn Seed' instead of 'corn_seed')
- Correct stat text/value alignment and font size in their respective boxes (they're currently snapped to the rect.topleft and are pretty small).

Other suggestions (might not be necessary after limiting the stats to just planted/harvested):
- Increase scrolling speed. It's currently set to ±2 pixels per event which required a lot of scrolling to get to the bottom of the list. 
- Lock the bounds of the scrolling capability as you can currently scroll the entire list off the screen in both directions.

**Comment by ylhs-262912** [comment]
Note: I asked sloukit independently what this feature wanted, as it was very unclear. here are those text convos:
image
image
image
image
so the first item doesn't apply. However, all the other concerns are valid. Given me a bit.

**Comment by DangerousVanilla** [comment]
I'm not sure I'm getting the same message you are (that the first thing doesn't apply). @sloukit, could you please clarify the intent on the round-end screen for me? The feature description (updated just yesterday) says: "Create simple round ending screen after every level (i.e., after every 15 minutes); **contains statistics on how many plants and fruit have been planted/harvested**".

My question is only around the second bold portion - do the messages between you two shown above indicate that this portion of the feature _isn't_ actually required?

**Comment by ylhs-262912** [comment]
All changes have been made!

**Comment by sloukit** [comment]
Hi, sorry for the confusion. The idea with the end of the round screen is to have a clear cut after 15 minutes and show the player the amount of crops and wood they currently have. This is cumulative, i.e. what the player owns goes into the next level and should also be included in the statistics. A 0 can be displayed for the crops the player doesn't have. I'm not sure I fully understand your question. Does this make it a bit clearer?

**Comment by DangerousVanilla** [comment]
Yes and no. Sorry if I'm seeming a bit dense here but I'm seeing multiple mechanics at play (starting inventory, buying/selling, planting/harvesting) and potential things to track and I'm affraid part of it is getting confused due to some potentially unfinished features and/or testing variables.

You start with some of everything currently but can then technically lose items through selling or planting seeds. Lets take your 5 starting corn seeds as an example and go through a couple scenarios to clarify what should be displayed at the end of a round...

Scenario 1:
1. You start with 5 corn seeds.
2. You do nothing for the entire round and end with the same 5 corn seeds.
Result opt. 1: You still have 5 corn seeds in your inventory so the round ending screen displays 5 corn seeds.
Result opt. 2: You didn't plant or harvest anything so the round ending screen shows 0 corn seeds.

Scenario 2:
1. You start with 5 corn seeds
2. You plant 3 of those corn seeds then wait for the round to end doing nothing else.
Result opt. 1: The round end screen shows 2 corn seeds because you have 2 in your inventory (having planted 3).
Result opt. 2: The round end screen shows 3 corn seeds because you planted 3 (2 remained in your inventory).
Result opt. 3: The round end screen shows 5 corn seeds because you still 'own' 5 corn seeds worth (2 in inventory and 3 planted)
Result opt. 4: The round end screen shows seperate categories for current inventory (2) and planted values (3), totaling to 5.

Scenario 3:
1. You start with 5 corn seeds
2. You go buy 45 more corn seeds so you have 50 total in your inventory.
3. You go plant 20 of these and realize your farm is full so you have no current use for the other 30 corn seeds.
4. You go back to the shop and sell 20 of those remaining 30 corn seeds leaving you with 10 in your inventory.
Result opt. 1: Round end shows 10 corn seeds because that's what you end with in your inventory.
Result opt. 2: Round end shows 30 corn seeds because you ended with 10 in inventory and 20 planted, meaning you currently 'own' 30 corn seeds worth. This would also indicate it doesn't matter what you buy/sell, just what you end the round with in inventory+planted/harvested.
Result opt. 3: Round end shows 20 corn seeds because you planted 20 corn seeds.
Result opt. 4: Round end shows 50 corn seeds because you had up to 50 in your inventory earlier and it doesn't keep track of what you sell.
Result opt. 5: Round end shows seperate categories for your invenotry and planted values, displaying 10 in inventory and 20 planted.
Result opt. 6: Round end tracks everything seperately (purchased, sold, ending inventory, planted, harvested) and shows them all and a calculated balance. If this was the case, would the balance show 10 (meaning it only cares about your inventory) 20 meaning it only cares about your planted/havested amounts which would be cummulative over the rounds as you mentioned, keeping track of total progress), 30 meaning it cares about your total current ownership (could still count planted/harvested cummulatively on this but adds your inventory value on top because you 'own' those) or something else entirely?


So that might seem like a lot but hopefully it illustrates my questions around what exactlly is supposed to be tracked/shown...


All that aside, the actual issue I was pointing out is simply that the values being displayed on the round-end screen are just wrong no matter how you look at it, but to fix that properly I think it will be important to clarify the intended outcome of the scenarios above if you don't mind.
The image below illustrates the actual issue I was trying to get at in this commit as is. It tracks two entire rounds of play testing with screenshots and explainations along the way:
round_end_inventory_issues

**Comment by ylhs-262912** [comment]
Round end menu now exactly copies inventory. Problem was it wasn't updating everything it was called, but only when it was initiated. It should fit at least 1 of the options now, however we need sloukit for further verification

**Comment by sloukit** [comment]
Thank you for the detailed description of your concerns. They are valid, and I'm sorry for the confusion and for not getting it sooner.

The end of round screen copies the inventory. The seeds that are currently planted (i.e. potential future fruit/potential money or former seeds) don't matter. The function of this end-of-round screen is not extremely important, it's more about having a clear signal that the round has ended and the next round will start now, and showing the player what they have in their inventory in case they never looked. Does this make sense to you? Please let me know if you have any other questions or concerns.

**Comment by sloukit** [comment]
This PR can be merged, but there are some conflicts between it and the main branch. @ylhs-262912 could you check this?

**Comment by ylhs-262912** [comment]
Ok, I'll resolve conflicts this afternoon.

**Comment by ylhs-262912** [comment]
Fixed the conflicts!
please acknowledge the changes have passed @sloukit and @DangerousVanilla so the merge can go through.

**Comment by sloukit** [comment]
There is a problem with the style-lint check, could you check it again?

**Review by DangerousVanilla — CHANGES_REQUESTED** [review]
Along with the lint formatting, it looks like this is going to need brought up to date with the main branch before testing can be done. 

The formatting seems like it's just a couple of whitespace lines to be removed.
Getting it up to speed with the main branch looks like it'll at least need an additional argument in the super().__init__ of RoundMenu class in menu_round_end.py.

**Comment by ylhs-262912** [comment]
try it now!

**Review by sloukit — APPROVED** [review]

**Comment by sloukit** [comment]
We can merge this branch once @DangerousVanilla has approved the changes

**Comment by DangerousVanilla** [comment]
@ylhs-262912, it looks like the boxes in the scrollable area aren't being cleared anymore as the screen is scrolled, would you mind taking a look at that please? Here's a short clip for reference:

https://github.com/user-attachments/assets/328a87b8-a041-4591-b381-1e91103630b2

**Comment by ylhs-262912** [comment]
Okay, I'll do it this afternoon

**Comment by ylhs-262912** [comment]
Done! try it now.

**Comment by ylhs-262912** [comment]
oop found a bug in the scrolling

**Comment by ylhs-262912** [comment]
fixed the scrolling bug. yip

**Comment by ylhs-262912** [comment]
Why did the lint fail this time?

**Comment by DangerousVanilla** [comment]
Taking a look at this now - I'll get you some details

**Comment by DangerousVanilla** [comment]
So after working around a long standing bug to actually get your latest updates I reran formatlint.py and all it did was remove a single blank line around line 46-47 in menu_round_end.py. 

That said, it looks like you're not quite up to date with main (there's still a lot of references to set_token_status in your commit. If you wouldn't mind syncing up with main, addressing any conflicts, and finally running formatlint.py again I think it'll have your all sorted out.

**Comment by ylhs-262912** [comment]
Okay, I'll do that.

**Comment by ylhs-262912** [comment]
oop its because I forgot to push a commit. that's where this all came from. oof. Tell me if there are anymore leftover references, I don't believe so.

**Comment by sloukit** [comment]
Looks good now. Can you approve, @DangerousVanilla?

**Review by DangerousVanilla — APPROVED** [review]
Looks great, thanks again for all the work on this one @ylhs-262912!

**Comment by DangerousVanilla** [comment]
@tomkommando, thank you for noticing the issue here - I'll look into it and see if I can fix that issue.

**Pull request merged**
