### PR TITLE
Taking the bath  sick face emoji

### PR DESCRIPTION
**Pull request by luvdamuzik**
Please go the the `Preview` tab and select the appropriate sub-template:

* Added a 15 second emote after leaving bath house

### CODE REVIEW

**Comment by luvdamuzik** [comment]
Only thing is i put sad_ani emote since there is no sick_ani. Once that is made i can change this quickly

**Comment by DangerousVanilla** [comment]
Hi @luvdamuzik, looks like I'm receiving an error that will need addressed in src\screens\switch_to_outgroup_menu.py, line 18. The super().__init__ there is missing an required argument 'set_token_status'. Not sure when your last fetch was but make sure that's up to date, then run formatlint.py and recommit please.

**Comment by luvdamuzik** [comment]
hey @DangerousVanilla i merged main with the fix. Basically this PR is done just need to change the emote called as soon as the asset is made.

**Review by DangerousVanilla — APPROVED** [review]
Looks great - we'll just have the emote updated when itss created like you mentioned.

**Pull request merged**
