### PR TITLE
Request for adding custom cursor 

### PR DESCRIPTION
**Pull request by bucket91**
## Summary

https://github.com/user-attachments/assets/a70c6168-7a97-4177-8925-26b6ab66a654
  .

### CODE REVIEW

**Comment by bucket91** [comment]
I don't get it I already formatted
Screenshot 2024-10-01 181107

**Comment by DangerousVanilla** [comment]
@bucket91, try using the formatlint.py file - just locate it a couple lines above main.py and run it. Should produce the following changes, then you can recommit:
image

**Comment by bucket91** [comment]
ahh was still using an older fork
will update and let you know its ready to review

**Comment by bucket91** [comment]
this should be good now

**Review by DangerousVanilla — APPROVED** [review]
Looks good!

**Comment by sloukit** [comment]
The main branch crashes after this merge. The error message is
`pygame-ce 2.5.1 (SDL 2.30.6, Python 3.12.1)
Traceback (most recent call last):
  File "/Users/sokitt/Documents/GitHub/pydew-valley-uzh/main.py", line 272, in <module>
    asyncio.run(game.run())
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/sokitt/Documents/GitHub/pydew-valley-uzh/main.py", line 236, in run
    mouse = pygame.image.load("images\\overlay\\Cursor.png")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No file 'images\overlay\Cursor.png' found in working directory '/Users/sokitt/Documents/GitHub/pydew-valley-uzh'.
psy-lifespan-clt006:pydew-valley-uzh sokitt$ 
`

@bucket91 could you please check this?

**Pull request merged**
