### PR TITLE
added scripted sequence: Group gatherings (triggered by ';')

### PR DESCRIPTION
**Pull request by HubertReX**
## Summary

This PR implements a scripted sequence: [Group gatherings](https://github.com/users/sloukit/projects/1/views/1?pane=issue&itemId=71232210) (triggered by `;`)

## Details

* emote can also be selected using the keyboard (`space`)
* now all 4 Scripted Sequences support both IN and OUT group gathering spot
* refactored `EmoteWheel` - customizable list of emotes, proper wheel drawing for any number of emotes
* `Player` and `NPC` need to have  `update_blocked` overloaded to handle emojis while blocked (used in Group gatherings sequence)

## Assumptions 

* if the number of voters (Player + NPCs from his active study group) is even and the votes are split half and half, Players vote wins (agreed with @sloukit)
* there is no large sprite bubble showing the selected crop - only text in the final dialog (agreed with @sloukit)
* this works only when triggered (`;`) on `farm_new` map (agreed with @sloukit)
* no actual group purchase on the market is made, and the result of vote must be saved somewhere and used later
* when triggered in OUT Group, the Player sprite becomes invisible and after a while gets horn and proper sprite - this bug was already in actual state of repo before this PR

## Media

https://github.com/user-attachments/assets/c689077d-764f-47c1-909b-030771f35293

## Checklist

- [x] I have tested this change locally and it works as expected.
- [x] I have made sure that the code follows the formatting and style guidelines of the project.

## Labels
`type: feature`, `area: scripted-sequence`

### CODE REVIEW

**Comment by sloukit** [comment]
For me, hitting the semicolon doesn't trigger the event. Instead, I saw that the other scripted sequences were a bit messed up: 

https://github.com/user-attachments/assets/8076211b-f14b-4736-b265-c1ace2be7a3d

@HubertReX could you check this again please?

**Comment by 13-Sonja** [comment]
@sloukit Try using "Ö" (or whatever you might have to the right of L) that's where a lot of keyboards have the ;

**Comment by sloukit** [comment]
Yes, I've tried everything, but it doesn't work, either on my work PC or on my laptop. I'll try to find out

**Comment by HubertReX** [comment]
I'll try to fix it tomorrow

**Comment by HubertReX** [comment]
with the latest commit, I just pushed, the premature scripted sequence end is fixed. However, I had to revert something that was supposed to fix another issue: In group gathering, when the emote wheel is opened, the player can press `e` and close the wheel without voting. I'm not able to distinguish whether the player voted or just closed the wheel and whatever option was active before voting will be counted as his vote. Unfortunately, his selection emote won't show. 

It is a bit of a corner case, so perhaps we shouldn't worry that much about it. What do you think?

**Comment by sloukit** [comment]
Thanks for your commitment! I think it's fine if we count "no vote" as a vote for the thing that was selected before the emote wheel was closed. We can make this n issue and work on it later

**Comment by sloukit** [comment]
Overall, it looks great to me! I like that the NPCs slowly walk away after the vote and the game continues. Just two things:
- The camera should zoom out to normal after the vote
- I can't move the player down after the scripted sequence (i.e. the direction arrow doesn't respond)

Could you take a look at these two things?

**Comment by HubertReX** [comment]
@sloukit 

I've fixed the camera zoom-out after voting.

I can't reproduce the problem with the player being unable to move after the scripted sequence. Can you record a video to demonstrate the whole context of the situation? Is it always like this or just after a sequence of events? Does it happen in all scripted sequences? Are other move directions working normally?

**Review by DangerousVanilla — APPROVED** [review]
This looks awesome and everything seems to work correctly from what I can tell. I also can't reproduce the issue of not being able to move after the scripted sequence.

@sloukit, if we can ensure this can work on your end too we'd be good to merge it.

**Comment by sloukit** [comment]
Looks great, thanks! We can merge it now, there is no problem with the arrow keys anymore

**Comment by sloukit** [comment]
@DangerousVanilla there is still a merge conflict, could you check this?

**Comment by DangerousVanilla** [comment]
@sloukit, definitely. All fixed. I had checked this out earlier but wouldn't let me save the resolution without also clicking commit so I just waited for your go-ahead.

**Comment by HubertReX** [comment]
after all merges, the game fails. There was some refactoring around images and overlay was renamed to UI. In order to make the game work again, there needs to be a change done in `level.py`:
- from:
>         for frame in TOMATO_OR_CORN_LIST:
>            self._emotes[frame] = [self.frames["overlay"][frame]]

- to:
>         for frame in TOMATO_OR_CORN_LIST:
>            self._emotes[frame] = [self.frames["items"][frame]]

should I create a PR for that?

**Pull request merged**
