### PR TITLE
Code refactoring and ability to reach resources from anywhere relative to the main script

### PR DESCRIPTION
**Pull request by fortwoone**
This pull request is a refactor and fix so the main script can access all the resources when executed normally. This should also make debugging from an IDE easier since running the current file will allow the working directory to be the global one for this project instead of the src subdirectory (renamed from code as the code name is used by a module in the Python standard library).

### CODE REVIEW

**Comment by meierman1** [comment]
I am getting an error with this one, any idea why this is?

```
Traceback (most recent call last):
  File "D:\git_repos\pydew-valley-uzh\main.py", line 57, in <module>
    game = Game()
           ^^^^^^
  File "D:\git_repos\pydew-valley-uzh\main.py", line 21, in __init__
    self.level = Level(self.tmx_maps, self.character_frames, self.level_frames, self.overlay_frames, self.font, self.sounds)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\git_repos\pydew-valley-uzh\src\level.py", line 30, in __init__
    self.setup(tmx_maps, character_frames, level_frames)
  File "D:\git_repos\pydew-valley-uzh\src\level.py", line 49, in setup
    Sprite((x * TILE_SIZE * SCALE_FACTOR, y * TILE_SIZE * SCALE_FACTOR), pygame.transform.scale_by(surf, SCALE_FACTOR), self.all_sprites, LAYERS['lower ground'])
  File "D:\git_repos\pydew-valley-uzh\src\sprites.py", line 11, in __init__
    self.rect = self.image.get_frect(topleft=pos)
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'pygame.surface.Surface' object has no attribute 'get_frect'. Did you mean: 'get_rect'?
```

**Comment by fortwoone** [comment]
@meierman1 you do not have the correct version of Pygame. You need to uninstall it and replace it with pygame-ce for this to work

**Comment by fortwoone** [comment]
Basically, a few years ago there has been an argument between the Pygame repository maintainer and the rest of the devs, so the project has been split off into two branches. The main Pygame one is basically dead now, and the other one is Pygame-CE which is maintained by the former devs

**Comment by meierman1** [comment]
perfect, thanks! funnily enough it worked with the old pygame package previously but I have now installed pygame-ce and it works like a charm! Will merge

**Pull request merged**
