### PR TITLE
New README

### PR DESCRIPTION
**Pull request by novialriptide**

### CODE REVIEW

**Comment by fortwoone** [comment]
@SSnowly did work on the code as well, so I think this should be accounted for in the README, otherwise LGTM

**Review by fortwoone — CHANGES_REQUESTED** [review]
(see previous comment)

**Comment by sloukit** [comment]
> @SSnowly did work on the code as well, and @RUposhcat did too on the tree recover feature (still WIP as far as I know), so I think this should be accounted for in the README, otherwise LGTM

Yep, I'll add all the other contributors today!

**Review by sloukit — CHANGES_REQUESTED** [review]
Updated team section: 
- [Sophie Kittelberger](https://github.com/sloukit), Project Director
- [larsbutler](https://github.com/larsbutler), Project Director, Game Developer, & Quality Analyst
- [bromeon](https://github.com/bromeon), Project Director, Game Developer, & Quality Analyst
- [novial](https://github.com/novialriptide), Game Developer & Quality Analyst
- [fortwoone](https://github.com/fortwoone), Game Developer & Quality Analyst
- [pmp-p](https://github.com/pmp-p), Game Developer & Quality Analyst
- [bydariogamer](https://github.com/bydariogamer), Game Developer
- [Brody Epstein](https://github.com/Eskimo396), Game Developer
- [Danilo Saiu](https://github.com/ultimateownsz), Game Developer
- [TMN_SGR](https://github.com/TMN-SGR), Game Artist
- [Adrienne Bradley](https://github.com/yoadrienne48), Game Artist
- [farg-eh](https://github.com/farg-eh), Game Artist & Game Developer
- [nteinert2005](https://github.com/nteinert2005), Game Artist & Game Developer
- [Evelin Toth](https://github.com/SSnowly), Game Artist & Game Developer
- [Leon](https://github.com/RUposhcat), Game Artist & Game Developer
- [MortalCoder](https://github.com/MortalCoder), Game Musician & Sound Designer
- [asterli6](https://github.com/asterli6), Game Musician & Sound Designer
- [Richard Nathaniel Effendy Kurniawan](https://github.com/richkdev), Game Developer, Game Musician, & Sound Designer
- [dee-a-go](https://github.com/dee-a-go), Game Developer, Game Musician, & Sound Designer

**Comment by novialriptide** [comment]
Updated + fixed the merge conflict.

**Pull request merged**
