### PR TITLE
 Add animal NPCs

### PR DESCRIPTION
**Pull request by HubertReX**
## Summary

This PR implements "Add animal NPCs" [task ](https://github.com/users/sloukit/projects/1/views/1?pane=issue&itemId=79059271).

This feature was basically already there, I reenabled animals and added some objects on the `Interactive` layer to block cows and chickens from leaving the range and prevent chickens from entering the barn.

`m1siU` started this task and he contributed here as well. 

Sorry for the mess in commits - I've pushed some of my local test files and had to revert them.

## Checklist

- [*] I have tested this change locally and it works as expected.
- [*] I have made sure that the code follows the formatting and style guidelines of the project.

## Labels
`type: feature`, `area: farm`, `area: town`

### CODE REVIEW

**Comment by sloukit** [comment]
This is fantastic! Great job, thanks to both of you. Can you add more chickens so that we have about 5 in each coop and 3 cows in the cow barns on the farm maps?

**Comment by HubertReX** [comment]
sure thing - done!

**Comment by DangerousVanilla** [comment]
When reviewing this I noticed the player's starting position changed - is that intentional?

**Comment by HubertReX** [comment]
My bad, I moved it for quicker testing. Sorry, for that. I can fix it tomorrow.

**Comment by DangerousVanilla** [comment]
No worries at all - thanks!

**Comment by sloukit** [comment]
Once the player position is fixed, we can merge this branch

**Comment by HubertReX** [comment]
player spawn point has been restored

**Review by DangerousVanilla — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
