### PR TITLE
Additional features minigame

### PR DESCRIPTION
**Pull request by luvdamuzik**
## Summary

Added 2 NPCs (very easy to add more) that cheer during the minigame. 

I moved the init of emote_manager from NPC to NPCBase so it can be used in NPCIndividualContext.
Made the NPC Idle and cheer from time to time. (In testing the best looking probability for cheering was 1/500)

## Checklist

- [x] Add as many NPCs as needed 
- [x] Add opponent from outgroup + AI to play
- [x] Change winning message

## Questions
1. What if the player is outgroup? Shouldnt the NPCs cheering be also outgroup?
2. Same logic applies to the opponent's group?
3. How many NPCs should be cheering?
4. To explain the Change wording when displaying score: "Your Group won!", no singular specifically the no singular part?

### CODE REVIEW

**Comment by sloukit** [comment]
@luvdamuzik great job, thanks! I think it would be nice to have at least 5 ingroup members next to the fence (as @michelfinley rightly said, the main idea of this thing is to create an atmosphere of "battle between groups", which should strengthen group affiliation – the more ingroup members there are, the better. Your cheering looks perfectly fine to me. 
- Could you add three more in-group NPCs? 
- The next step is to have some behaviour sets for the outgroup NPCs to play "against" the player, and add 5 rooting outgroup NPCs next to the opponent's fence.

**Comment by luvdamuzik** [comment]
Great i added 5 NPCs per group on their respective sides and also made it so that the player depending on group spawns on the correct side. Same as the opponent. Now that is left is to make the cows collidable on the outgroup side and the AI for the opponent.

**Comment by sloukit** [comment]
Perfect! The only thing that could be adjusted: @luvdamuzik Could you change the state of the camera, zoom it out a bit more, so that the player always sees the outgroup members next to the fence on the right?

**Review by DangerousVanilla — APPROVED** [review]
Looks great! Once sloukit's requested change to the camera is implemented I can merge this.

**Pull request merged**
