### PR TITLE
plants assets, image folder refactor, removed drops, started level system

### PR DESCRIPTION
**Pull request by ylhs-262912**
Please go the the `Preview` tab and select the appropriate sub-template:

* [Changes](?expand=1&template=code_pr_template.md) 

added assets from asset pack
Refactored image folder
removed drop functionality
started level level system framework

* [Documentation](?expand=1&template=docs_pr_template.md)
added these assets:
image
image
Video comparison of the image file refactor:
Before -
https://github.com/user-attachments/assets/a69b4c3f-06f5-4967-b426-af0c2bd8330c
After -
https://github.com/user-attachments/assets/8f1c465b-6c16-49ce-bf9f-3dd063048952
This was mostly done to remove confusion.

I removed the existing drop system. this means trees no longer drop items on to the ground. Instead, when destroyed, they directly appear in the player's inventory. 
Video Demonstration: 
https://github.com/user-attachments/assets/49fa737b-49df-44ba-a3a8-587dfe5bdf0d

I created the skeleton of the level system:
the main has a  image variable.
this is used by the following three functions in the main:
image
-for updating of round variable through debug triggers:
image
-for normal updating of the round variable:
image
these functions can be used as parameters in classes to be called outside of main.
Right now, the round increments with the round end menu and updates the earthquake effect.
Video Demonstration:
https://github.com/user-attachments/assets/5fe7c857-af94-4fb7-a632-e899b342c31d
image

Note: all changes were approved by sophie before this PR was made. If you want the full DMs between me and sophie regarding this PR just ask.

### CODE REVIEW

**Comment by sloukit** [comment]
Can you please fetch this branch? There are some conflicts with older merges. Thanks!

**Comment by ylhs-262912** [comment]
image
can't start merge conflict process yet

**Review by sloukit — APPROVED** [review]

**Review by DangerousVanilla — CHANGES_REQUESTED** [review]
@ylhs-262912, thank you for the tremendous amount of work on this, great changes overall.

This brought to light a couple long standing issues, neither were caused by you but I wonder if you might be able to quickly address them since they're directly related to files you just changed.

Basically, it looks like the tomato_seed.png file is missing it's outline.
And the corn/wheat images have been swapped with each other.
I looked deeper into this and both of these have been issues since the original clear-code-projects upload that we forked from!

Here's a quick visual of the issues:
requested_corrections

The original asset pack has these for corn and wheat as reference:
conr_wheat_mixup

**Comment by ylhs-262912** [comment]
image
it's still giving me an error, so its possible that the image folder refactor stops github's built in merge conflict resolver from working.

**Comment by ylhs-262912** [comment]
got it

**Review by sloukit — APPROVED** [review]

**Comment by DangerousVanilla** [comment]
Thanks @ylhs-262912, looks great! I'll see if I can figure out it's conflict issues.

**Review by DangerousVanilla — APPROVED** [review]

**Comment by DangerousVanilla** [comment]
@ylhs-262912, @sloukit, my apologies, I can't believe I still missed this after so many reviews of this... This PR looks like it caused an issue for the fruit images on trees and bushes.
image
@ylhs-262912, do you think you could address this? I'm not sure if there are other images needing created or if it's just a matter of pointing these to the right ones, but it obviously doesn't look right anymore.

**Comment by ylhs-262912** [comment]
don't worry about it, sloukit said it was fine
image
if it really bothers you, you can put it as a new issue or change it directly.

**Pull request merged**
